### ISSUE TITLE
Modifying the message in a stage will result in panic

### ISSUE THREAD

**Issue by softexpert** [usedatabrew/tango#1]
Hello and thank you for your contribution to the community !

I have probably misunderstood how it is supposed to work - modifying the message will immediately result in panic.

What am I doing wrong ?

Here is my modification of the sample code:

```go
package main

import (
	"fmt"
	"time"

	"github.com/usedatabrew/tango"
)

func main() {
	instance := tango.NewTango()

	stages := []tango.Stage{
		{
			Channel: make(chan interface{}),
			Function: func(msg interface{}) (interface{}, error) {
				return fmt.Sprintf("%v stage 1", msg), nil
			},
		},
		{
			Channel: make(chan interface{}),
			Function: func(msg interface{}) (interface{}, error) {
				if msg.(int)%5 == 0 {
					time.Sleep(time.Millisecond * 10)
				}
				return fmt.Sprintf("%v stage 2", msg), nil
			},
		},
		{
			Channel: make(chan interface{}),
			Function: func(msg interface{}) (interface{}, error) {
				return fmt.Sprintf("%v stage 3", msg), nil
			},
		},
	}

	instance.SetStages(stages)

	instance.OnProcessed(func(i interface{}, err error) {
		if err != nil {
			_ = fmt.Errorf("messages happened in the last stage %v", err)
		}
		fmt.Println("Message processed", i)
	})

	producerChannel := make(chan interface{})

	go func() {
		for i := 0; i <= 10000000; i++ {
			producerChannel <- fmt.Sprintf("item %v", i)
			time.Sleep(time.Millisecond * 200)
		}
	}()

	// Tango will consume messages from the producer channel and
	// pass them through the stages.
	instance.SetProducerChannel(producerChannel)

	if err := instance.Start(); err != nil {
		panic(err)
	}
}

```
Running this code will panic:
```
$ go run main.go 
panic: interface conversion: interface {} is string, not int

goroutine 35 [running]:
main.main.func2({0x4ffce0?, 0xc000194010?})
        /home/user/go/src/testTango/main.go:23 +0xcd
github.com/usedatabrew/tango.(*Tango).Start.func1(0x1)
        /home/user/go/pkg/mod/cache/github.com/usedatabrew/tango@v0.0.5/tango.go:86 +0x171
created by github.com/usedatabrew/tango.(*Tango).Start in goroutine 1
        /home/user/go/pkg/mod/cache/github.com/usedatabrew/tango@v0.0.5/tango.go:75 +0x125
exit status 2
```

Thanks for your enlightening !

**Comment by le-vlad** [comment]
Hey @SoftExpert 
Thanks for your question.

From what I see here you are pushing a string to the first stage 
`producerChannel <- fmt.Sprintf("item %v", i)`

But stage number 2 treats your message as `int` 
Therefore you receive panic. 
```golang
if msg.(int)%5 == 0 {
    time.Sleep(time.Millisecond * 10)
}
return fmt.Sprintf("%v stage 2", msg), nil
```

**Comment by softexpert** [comment]
Indeed, right you are !
Rookie mistake I have committed ! Thanks for spotting it and sorry for the false alert !
Cheers and good luck with your further developments !

--

I have one totally different question - how could the processing be parallelized ?
Supposing that the producer can push 10 items/second, but stage 2 takes, let's say 5 seconds to complete, and you need to process 50 000 items, you end up spending a lot of time until the last item is consumed.
Could the processing be parallelized ? 
Perhaps specifying a number of parallel routines that could, each, execute all the stages but on different items picked from the producer's queue ?
It would be convenient to be able to do this with a simple setting, when initializing the Tango object.
What do you think the best approach would be : a global producer with a configurable Tango or a global producer with a dispatcher that feeds a number of Tangos, each in their own goroutine ?

Anyway, cheers !

**Comment by le-vlad** [comment]
@SoftExpert 
I believe that the processing could be parallelized but, I'll have to think about the way to synchronize the messages since I want to keep the ordering of the messages. 
This is something that I'm thinking about, but right now can't say for sure when or how it's going to be implemented. 

But this is definitely one of the things to consider in case we have slow stages

**Comment by le-vlad** [comment]
@SoftExpert Regarding starting multiple Tangos using the dispatcher feels great but, only as an external package that orchestrates the tango queues. 
Therefore you will be able to create multiple queues that will be executed in parallel.  But it will not help if you have to keep message ordering.
